services:
  app:
    image: tilalx/quotes-rest:latest
    container_name: quotes-rest
    ports:
      - "7080:80"
    environment:
        #postgresql
      - PGHOST=quotes-db
      - PGPORT=5432
      - PGDATABASE=quotes
      - PGDBUSER=postgres
      - PGDBPASSWORD=secretpassword
      - PGSSL=true
      - PGSSLMODE=prefer
      - PGCONNECTTIMEOUT=30
    restart: always

  quotes-db:
    image: postgres:17
    container_name: quotes-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: quotes