services:
  app:
    image: tilalx/quotes-rest:latest
    container_name: quotes-rest
    ports:
      - "7080:80"
    environment:
        #postgresql
      - PGHOST=192.168.178.212
      - PGPORT=5432
      - PGDATABASE=quotes
      - PGDBUSER=postgres
      - PGDBPASSWORD=password
      - PGSSL=false
      - PGSSLMODE=prefer
      - PGCONNECTTIMEOUT=30